### ISSUE TITLE
Dishes work in wrappers but not in the cookbook for the given dish

### ISSUE THREAD

**Issue by miroswan** [phs/dishes#10]
To avoid confusion, i'm going to define some things first:
- add cookbook: Adds desired configs
- wash cookbook: Washes configs
- wrapper cookbook: Contains dish/sink code

When I add both the wrapper and add cookbooks to a node's run list, I get the expected behavior when I remove the add cookbook from the run list. The subsequent converge includes the wash cookbook and the node state transforms appropriately. 

However, if I do not use a wrapper cookbook and place the dish/sink code in the add cookbook itself, I the wash code is not included in the converge following the removal of the add cookbook. This might be the expected behavior, but the docs led me to believe otherwise. Just a heads up.

**Comment by phs** [comment]
From the `README`:

> While dishes leave traces of themselves behind in the Chef server, sinks do not. Therefore if the recipe containing dishes_sink is removed, nothing gets clean. Though one might imagine a dedicated service to wash the dirty dishes even if the sink recipe is absent, this is currently out of scope.
